@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.magneticraft2.common.multiblock;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;