@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.magneticraft2.common.multiblock.generic;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;